# Generated by Django 3.2.9 on 2021-11-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='likes',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch_count',
            field=models.IntegerField(default=0),
        ),
    ]
