# Generated by Django 3.2.9 on 2021-11-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='banner',
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
