# Generated by Django 3.2.9 on 2021-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
