# Generated by Django 3.2.9 on 2021-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20211108_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='cast',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile/images'),
            preserve_default=False,
        ),
    ]
