# Generated by Django 3.2.9 on 2021-11-08 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_review_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='cast',
            name='id_name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='movies.idnumber'),
            preserve_default=False,
        ),
    ]
