# Generated by Django 3.2.9 on 2021-11-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20211108_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='id_name',
        ),
        migrations.DeleteModel(
            name='IdNumber',
        ),
    ]
