# Generated by Django 3.2.9 on 2021-11-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20211109_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='number',
            field=models.CharField(max_length=150),
        ),
    ]
