# Generated by Django 3.2.9 on 2021-11-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='id_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.id'),
            preserve_default=False,
        ),
    ]
